name: Test Vatten

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Installera requests
        run: |
          pip install requests

      - name: Kör test_vatten.py
        run: |
          python3 test_vatten.py
