name: Weather Update

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Hämta alla modeller
        run: |
          mkdir -p temp

          curl "https://api.open-meteo.com/v1/forecast?latitude=60.136&longitude=13.006&models=icon_global&hourly=temperature_2m,surface_pressure,wind_speed_10m,wind_direction_10m,precipitation_probability,precipitation&forecast_days=2" -o temp/icon_global.json

          curl "https://api.open-meteo.com/v1/forecast?latitude=60.136&longitude=13.006&models=gfs_global&hourly=temperature_2m,surface_pressure,wind_speed_10m,wind_direction_10m,precipitation_probability,precipitation&forecast_days=2" -o temp/gfs_global.json

          curl "https://api.open-meteo.com/v1/forecast?latitude=60.136&longitude=13.006&models=gem_global&hourly=temperature_2m,surface_pressure,wind_speed_10m,wind_direction_10m,precipitation_probability,precipitation&forecast_days=2" -o temp/gem_global.json

          curl "https://api.open-meteo.com/v1/forecast?latitude=60.136&longitude=13.006&models=icon_eu&hourly=temperature_2m,surface_pressure,wind_speed_10m,wind_direction_10m,precipitation_probability,precipitation&forecast_days=2" -o temp/icon_eu.json

          curl "https://api.open-meteo.com/v1/forecast?latitude=60.136&longitude=13.006&models=dmi_seamless&hourly=temperature_2m,surface_pressure,wind_speed_10m,wind_direction_10m,precipitation_probability,precipitation&forecast_days=2" -o temp/dmi_seamless.json

          curl "https://api.open-meteo.com/v1/forecast?latitude=60.136&longitude=13.006&models=best_match&hourly=temperature_2m,surface_pressure,wind_speed_10m,wind_direction_10m,precipitation_probability,precipitation&forecast_days=2" -o temp/best_match.json

      - name: Visa filer
        run: ls -la temp
      - name: Skapa weather.json
        run: |
          echo '{' > weather.json
          echo '"updated":"test"' >> weather.json
          echo '}' >> weather.json

      - name: Spara till GitHub
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add weather.json

          git commit -m "Update weather cache" || true

          git push
